service:
  name: poker-player-service

plugins:
  - serverless-webpack
  - serverless-kms-secrets
  - serverless-offline

custom:
  webpack:
      packager: yarn
  serverless-kms-secrets:
      secretsFile: config/env/secrets/${opt:stage, self:provider.stage}.yml
  secrets: ${file(config/env/secrets/${opt:stage, self:provider.stage}.yml):secrets}

provider:
  name: aws
  runtime: nodejs8.10

functions:
  get-poker-players: ${file(config/functions/poker-player.yml):get}
  put-poker-player: ${file(config/functions/poker-player.yml):put}
