service:
  name: poker-player-service

plugins:
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-kms-secrets
  - serverless-offline

custom:
  webpack:
      packager: yarn
  documentation:
      models: ${./docs/models.yaml}
  serverless-kms-secrets:
      secretsFile: config/env/secrets/${opt:stage, self:provider.stage}.yml
  secrets: ${file(config/env/secrets/${opt:stage, self:provider.stage}.yml):secrets}

provider:
  name: aws
  timeout: 10
  runtime: nodejs8.10
  environment:
    SERVICE_NAME: poker-player-service
    NODE_ENV: ${opt:stage}

functions:
  get-poker-players: ${file(config/functions/poker-player.yml):get}
  put-poker-player: ${file(config/functions/poker-player.yml):put}
  delete-poker-player: ${file(config/functions/poker-player.yml):delete}